### ISSUE TITLE
<bug>: Issue Templates don't appear 

### ISSUE THREAD

**Issue by CBID2** [YurisCodingClub/accessibility-mentor#47]
## Problem
I noticed that when I click on the "New Issue" button, the templates don't appear. This can caused contributors to be confused. 

## Proposed Solution
According to [the little note in the Configuring Template Chooser section of GitHub's Docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser), the issue templates will work by by adding a `config.yml` file to the `.github/ISSUE_TEMPLATE` folder and setting `blank_issues_enabled` to `false`. 
**Update**: I realized that some of the syntax in the issue templates were not correct, so I'm going to redo them an see.

## Additional Information
I would like to work on this issue @YuriDevAT.  
```[tasklist]
### Tasks
- [ ] https://github.com/YurisCodingClub/accessibility-mentor/issues/50
- [ ] https://github.com/YurisCodingClub/accessibility-mentor/issues/51
- [ ] https://github.com/YurisCodingClub/accessibility-mentor/issues/52
```

**Comment by YuriDevAT** [comment]
Thank you for opening these bug issues @CBID2. Please do not start working on issues which are not assigned to you or labeled by maintainers (see [contribution guideline](https://github.com/YurisCodingClub/accessibility-mentor/blob/main/CONTRIBUTING.md))

We want to give every one the chance to work on issues and try to avoid having on contributor assigned to more than one issue at one time.

**Comment by CBID2** [comment]
Hi @YuriDevAT. I'm confused. You assigned this issue to me yesterday. 🤔

**Comment by YuriDevAT** [comment]
Yes, but you opened three new ones #50 #51 #52 . Certain things should be discussed, if you have the feeling to divide them into three separate issues. New bug issues have to be revised first by maintainers, if they agree, get labels on them and such, and then be assigned. It is okay to do all these changes in one PR as your first bug request was meant to.

**Comment by CBID2** [comment]
Ohhh I see @YuriDevAT

**Comment by YuriDevAT** [comment]
Config.yml is actually not needed to make the issue templates appear. There was simply a misconfiguration on the repo. I will rewrite the tickets #51 and #53 to keep track of the changes needed in order to work, and assign them to you.

**Comment by YuriDevAT** [comment]
> Ohhh I see @YuriDevAT. Those correlate to the main one. I learned that doing small PRs are effective for issues like this from my time at OpenSauced. This [blog post](https://blog.codacy.com/small-pull-requests) helped me with this too. Nonetheless, I'll do it as one PR like you requested and discuss my suggestion in the future

And that is totally valid. Nethertheless, there is a contribution guideline which everyone has to follow in other to make working smooth for everyone. It would have been great to suggest this on the issue directly, add the "discussion" label to this issue or use the discussion section of the repository for raising this idea. In the end, the maintainer is the one you makes the decisions, and I am sure, every maintainer is open for discussions, eager to learn new things and ways to improve.
