### ISSUE TITLE
[BUG] Layout structure not following guide

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/accessibility-mentor#49]
### Description
In the `index.js` file the layout structure currently shows following output for the content perceived through the DOM
```
<main>
 <Header />
 <Content />
 <Hero />
</main>
```

This is misleading for screen reader users. The typical structure is
```
<header>
<main>
<footer>
```

```[tasklist]
### Tasks
- [ ] Remove landmark tags (like header, footer, aside) from the main 
- [ ] the `<Header />` components appears before the `<main>` tag
- [ ] `<Content />` and `<Hero />` components stay inside the `<main>` since they are containing the information of the main content
```

**Comment by rawasaditya** [comment]
I can work on this assign it to me, although you comment says remove landmark tags (aside) it is in Content component do you want me to change it to div ? of like move it outside Content component, if you want me to move it out where should aside go ? 
Thanks

**Comment by CBID2** [comment]
Hi @YuriDevAT! :)  I already finished creating the PRs for #47, so can I work on this issue once they are merged? I had a great time working on the footer, and want to continue to growing my coding skills through contributing to this project. Just like I promised on Linkedin! :)
